### PR TITLE
Update _pages.scss

### PR DESCRIPTION
**Pull request by gitsang**

### CODE REVIEW

**Comment by h-enk** [comment]
@gitsang, ?!

**Comment by gitsang** [comment]
The markdown image is displayed in its original size, which will make the picture fill the entire screen.

```
img {
    max-width: 100%;
    max-height: 100%;
}
```

maybe this can fix it

**Comment by gitsang** [comment]
failed by lint, I will close this PR

**Comment by h-enk** [comment]
> The markdown image is displayed in its original size, which will make the picture fill the entire screen.
> 
> ```
> img {
>     max-width: 100%;
>     max-height: 100%;
> }
> ```
> 
> maybe this can fix it

Are you using one of the [image shortcodes](https://getdoks.org/docs/recipes/images/)? They both use the `img-fluid` class: https://getbootstrap.com/docs/4.6/content/images/#responsive-images

Note) You could also add the `img-fluid` class to an ` tag yourself.

**Comment by gitsang** [comment]
No, I add image in markdown like `img`
So if I `hugo`(or `npm run build`) directly, image can stay in wrong size.



And Thanks, I will try `img-fluid`

**Pull request closed without merging**
