### PR TITLE
Restructure Doks

### PR DESCRIPTION
**Pull request by h-enk**
## Summary

Doks is a documentation theme for Hyas, a Hugo-powered Jamstack framework for building production-ready websites.

### npm packages

- [@hyas/core](https://www.npmjs.com/package/@hyas/core)
- [@hyas/seo](https://www.npmjs.com/package/@hyas/seo)
- [@hyas/images](https://www.npmjs.com/package/@hyas/images)
- [@hyas/themes-doks](https://www.npmjs.com/package/@hyas/themes-doks)

## Basic example

https://deploy-preview-881--doks.netlify.app/

## Motivation

Why are we doing this? What use cases does it support? What is the expected outcome?

## Checks

- [x] Read [Create a Pull Request](https://getdoks.org/docs/contributing/how-to-contribute/#create-a-pull-request)
- [x] Supports all screen sizes (if relevant)
- [x] Supports both light and dark mode (if relevant)
- [ ] Passes `npm run test`

### CODE REVIEW

**Comment by ilovesusu** [comment]
When will it be available in the latest version

**Comment by h-enk** [comment]
That will be soon /I guess it will be next week

**Comment by ilovesusu** [comment]
?

**Comment by h-enk** [comment]
Yeah, I know. The code is there (for a while). Working hard on documentation — is really needed before releasing. Unfortunately, can't give you a date (but know it has my priority). Thanks for your patience.

**Comment by h-enk** [comment]
https://github.com/h-enk/doks/pull/1043

**Pull request closed without merging**
