### PR TITLE
Add shortcodes for Mermaid & PlantUML diagrams

### PR DESCRIPTION
**Pull request by thanh-vinh**
### Added
- Add `mermaid` & `plantuml` shortcodes
- Add examples in `docs`
- Options: `plantuml` and `mermaid` in `/config/_default/params.toml`

### Changed

- Markdown lint: disable `MD040` - Fenced code blocks should have a language specified

### CODE REVIEW

**Comment by OCram85** [comment]
@thanh-vinh: Awesome, could mermaid be integrated via node module to prevent loading external js?

**Comment by h-enk** [comment]
@thanh-vinh, thanks for your work — appreciated! 

Doks uses npm to centralize (and localize) all dependencies. So, that also would need to be the route for Mermaid + PlantUML. See e.g. https://github.com/h-enk/doks/blob/master/layouts/partials/footer/script-footer.html

Doks adds supportive functionalities as an option. So, that also applies to Mermaid and PlantUML. See e.g. the options section: https://github.com/h-enk/doks/blob/master/config/_default/params.toml

If you need help with that, let me know.

And, as I'm not sure about PlantUML yet (a/o latest commit 2 years ago), I would very much like to see the PR split.

What are your main reasons for PlantUML (next to Mermaid)?

@OCram85, what are your thoughts on PlantUML?

**Comment by OCram85** [comment]
I can't say much about PlantUML. It's new to me, so I'm not really representativ ^^

> 💡  Maybe #242 helps here...

**Comment by thanh-vinh** [comment]
The PR has been udpated!
- Use `npm` for dependencies
- Add `options` for them

> 
> What are your main reasons for PlantUML (next to Mermaid)?
> 
@h-enk  [PlantUML ](https://plantuml.com/)has more diagram types than Mermaid. So, we can use PlantUML for some specific diagrams that not available in Mermaid.

**Comment by andrew-somervell** [comment]
How's this going? Need a hand @h-enk ? 🙏🏼

**Comment by h-enk** [comment]
@thanh-vinh, super thanks for your efforts. However, to speed things up, I'm going to close your PR and go forward w/ https://github.com/h-enk/doks/pull/369

I've looked into PlantUML, but for now I don't see reasons for implementing this (most Doks users asked for Mermaid explicitly). Aside from that (also applies to Mermaid), I think generating charts and diagrams for use at build time (see also: [At build time](https://getdoks.org/docs/extensions/mermaid/#at-build-time)) is a smarter way (a/o for performance reasons) than at request time (if that's possible).

@andrew-somervell, I would like to see https://github.com/h-enk/doks/pull/369 extended w/ a Mermaid theme switch respecting the dark /light toggle (so, default Mermaid theme when toggled light, and dark Mermaid theme when toggled dark). See also e.g. [Drawing diagrams in Sanity with Mermaid.js](https://raymondjulin.com/blog/drawing-diagrams-in-sanity-with-mermaid-js). Don't know if you can help w/ that?

**Pull request closed without merging**
